"use client";

import { useEffect, useState } from "react";
import { Copy, Check, Link2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Alert } from "@/components/ui/alert";
import { sendQuotationToCustomerAccountAction } from "@/app/actions/quotations";

/**
 * "Share this quotation" (Update 2) — sits inside the existing Quotation
 * Details popup, below the totals/status info and above Close/Print/
 * Approve. The Quotation Link reuses the app's existing view-only
 * DocumentShareLink mechanism (auto-generated by getQuotationDetailAction,
 * see quotation-detail.ts's doc comment) — this component only presents
 * it and offers Copy Link, it never generates or revokes anything itself.
 * Send to Customer is a separate, narrower action (sendQuotationToCustomerAccountAction)
 * that delivers the quotation into the customer's own account — never an
 * email — and is only rendered at all when the customer has an activated
 * account and the quotation is still eligible to be sent.
 */
export function QuotationSharePanel({
  quotationId,
  shareToken,
  customerHasActivatedAccount,
  canSendToCustomerAccount,
  onSent,
}: {
  quotationId: string;
  shareToken: string;
  customerHasActivatedAccount: boolean;
  canSendToCustomerAccount: boolean;
  onSent: () => void;
}) {
  const [url, setUrl] = useState("");
  const [copied, setCopied] = useState(false);
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setUrl(`${window.location.origin}/documents/${shareToken}`);
  }, [shareToken]);

  async function copyLink() {
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      setError("Couldn't copy automatically — please select and copy the link manually.");
    }
  }

  async function handleSend() {
    setSending(true);
    setError(null);
    const result = await sendQuotationToCustomerAccountAction(quotationId);
    setSending(false);
    if (!result.ok) {
      setError(result.error);
      return;
    }
    setSent(true);
    onSent();
  }

  return (
    <section className="space-y-3 rounded-md border border-slate-200 p-3 sm:p-4">
      <div className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-brand-700">
        <Link2 className="h-3.5 w-3.5" />
        Share this quotation
      </div>

      {error && <Alert tone="error">{error}</Alert>}

      <div>
        <p className="mb-1 text-xs font-medium text-slate-500">Quotation Link (View Only)</p>
        <div className="flex flex-wrap items-center gap-2">
          <Input readOnly value={url} className="min-w-0 flex-1 text-xs sm:text-sm" onFocus={(e) => e.currentTarget.select()} />
          <Button type="button" size="sm" variant="outline" onClick={copyLink} className="shrink-0">
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />} {copied ? "Copied" : "Copy Link"}
          </Button>
        </div>
        <p className="mt-1 text-xs text-slate-400">Anyone with this link can view the quotation. They cannot edit or approve it.</p>
      </div>

      {sent ? (
        // Persists once a send actually succeeds, even after the parent's refetch
        // (refreshAfterMutation) brings back canSendToCustomerAccount: false because
        // the quotation is no longer DRAFT/REVISION_REQUESTED — otherwise the success
        // feedback the spec requires would flash and vanish the instant the popup
        // picks up its own live update.
        <div className="rounded-md bg-success-50 p-3">
          <p className="text-xs text-success-800">
            <span className="font-medium">Sent.</span> This quotation now appears in the customer&apos;s account.
          </p>
        </div>
      ) : canSendToCustomerAccount ? (
        <div className="flex flex-wrap items-center gap-2 rounded-md bg-success-50 p-3">
          <p className="min-w-0 flex-1 text-xs text-success-800">
            <span className="font-medium">This customer has an activated account.</span> Send this quotation directly to their
            account. It will appear in their Quotations section.
          </p>
          <Button type="button" size="sm" onClick={handleSend} disabled={sending} className="shrink-0">
            {sending ? "Sending..." : "Send to Customer"}
          </Button>
        </div>
      ) : (
        !customerHasActivatedAccount && (
          <div className="rounded-md bg-slate-50 p-3">
            <p className="text-xs text-slate-600">
              This customer does not have an activated account. You may share the quotation link above manually.
            </p>
          </div>
        )
      )}
    </section>
  );
}
