import { redirect } from "next/navigation";
import { requireUser } from "@/lib/session";
import { can } from "@/lib/permissions-guard";
import { formatCurrency, formatDateTime } from "@/lib/utils";
import { DocumentShell, DocumentField, DocumentSection } from "@/components/documents/document-shell";
import { resolvePeriodRange, computeTransactionSummary, type PeriodType } from "@/lib/transaction-summary";

export default async function TransactionSummaryPrintPage({ searchParams }: PageProps<"/reports/summary/print">) {
  const user = await requireUser();
  const isStaffLike = user.role === "STAFF" || user.role === "ADMIN";
  if (!isStaffLike) redirect("/dashboard");
  if (user.role === "STAFF" && !(await can(user, "REPORTS_EXPORT"))) redirect("/reports/summary");

  const sp = await searchParams;
  const sel = {
    type: (typeof sp.type === "string" ? sp.type : "monthly") as PeriodType,
    date: typeof sp.date === "string" ? sp.date : undefined,
    month: typeof sp.month === "string" ? sp.month : undefined,
    year: typeof sp.year === "string" ? Number(sp.year) : undefined,
    quarter: typeof sp.quarter === "string" ? Number(sp.quarter) : undefined,
    half: typeof sp.half === "string" ? Number(sp.half) : undefined,
  };
  const range = resolvePeriodRange(sel);
  const summary = await computeTransactionSummary(range);

  return (
    <DocumentShell title="Transaction Summary" documentNumber={range.label}>
      <DocumentSection title="Reporting Period">
        <p className="text-sm text-slate-700">{range.label}</p>
      </DocumentSection>

      <DocumentSection title="Summary">
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
          <DocumentField label="Total Inquiries" value={summary.totalInquiries} />
          <DocumentField label="Total Quotations" value={summary.totalQuotations} />
          <DocumentField label="Total Orders" value={summary.totalOrders} />
          <DocumentField label="Total Invoices" value={summary.totalInvoices} />
          <DocumentField label="Total Payments" value={summary.totalPayments} />
          <DocumentField label="Sales / Revenue" value={formatCurrency(summary.salesRevenue)} />
          <DocumentField label="Outstanding Balance" value={formatCurrency(summary.outstandingBalance)} />
          <DocumentField label="Cancelled" value={summary.cancelled} />
          <DocumentField label="Completed" value={summary.completed} />
        </div>
      </DocumentSection>

      <DocumentSection title="Transaction Breakdown — Orders by Status">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-left text-xs uppercase tracking-wide text-slate-400">
              <th className="py-1">Status</th>
              <th className="py-1 text-right">Count</th>
            </tr>
          </thead>
          <tbody>
            {summary.ordersByStatus.map((s) => (
              <tr key={s.status} className="border-b border-slate-100">
                <td className="py-1">{s.status.replace(/_/g, " ")}</td>
                <td className="py-1 text-right tabular-nums">{s.count}</td>
              </tr>
            ))}
            {summary.ordersByStatus.length === 0 && (
              <tr>
                <td colSpan={2} className="py-2 text-slate-400">
                  No orders in this period.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </DocumentSection>

      <DocumentSection title="Transaction Breakdown — Confirmed Payments by Method">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-left text-xs uppercase tracking-wide text-slate-400">
              <th className="py-1">Method</th>
              <th className="py-1 text-right">Total</th>
            </tr>
          </thead>
          <tbody>
            {summary.paymentsByMethod.map((p) => (
              <tr key={p.method} className="border-b border-slate-100">
                <td className="py-1">{p.method.replace(/_/g, " ")}</td>
                <td className="py-1 text-right tabular-nums">{formatCurrency(p.total)}</td>
              </tr>
            ))}
            {summary.paymentsByMethod.length === 0 && (
              <tr>
                <td colSpan={2} className="py-2 text-slate-400">
                  No confirmed payments in this period.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </DocumentSection>

      <DocumentSection title="Report Information">
        <p className="text-xs text-slate-500">
          Generated by {user.name} on {formatDateTime(new Date())}
        </p>
      </DocumentSection>
    </DocumentShell>
  );
}
