import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { requireUser } from "@/lib/session";
import { can } from "@/lib/permissions-guard";
import { getCurrentCustomer } from "@/lib/current-customer";
import { prisma } from "@/lib/prisma";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, THead, TBody, TR, TH, TD } from "@/components/ui/table";
import { formatCurrency, formatDate } from "@/lib/utils";
import { computeStatementOfAccount, deriveSoaBalanceStatus } from "@/lib/soa";
import { findActiveShareLink } from "@/lib/document-sharing";
import { DocumentShareManager } from "@/components/documents/document-share-manager";
import { SendSoaButton } from "./send-soa-button";
import { DiscussSoaButton } from "./discuss-soa-button";

const STATUS_TONE = { CURRENT: "blue", DUE: "yellow", OVERDUE: "red" } as const;

export default async function SoaViewPage({ params }: PageProps<"/soa/view/[id]">) {
  const user = await requireUser();
  const isStaffLike = user.role === "STAFF" || user.role === "ADMIN";

  const { id } = await params;
  const statement = await prisma.statementOfAccount.findUnique({ where: { id }, include: { customer: true, generatedBy: true } });
  if (!statement) notFound();

  // A customer clicking their own "Statement of Account Available"
  // notification must land here directly (spec: "the customer should
  // immediately see the relevant SOA," not get bounced to the dashboard) —
  // mirrors the same ownership check already used by /soa/[id]/print.
  if (!isStaffLike) {
    const customer = await getCurrentCustomer(user.id);
    if (statement.customerId !== customer.id) redirect("/payments");
  } else if (user.role === "STAFF" && !(await can(user, "SOA_VIEW"))) {
    redirect("/dashboard");
  }
  const canShare = user.role === "ADMIN" || (isStaffLike && (await can(user, "SOA_SHARE")));

  const [computation, openOrders, activeShareLink] = await Promise.all([
    computeStatementOfAccount(statement.customerId, statement.periodStart, statement.periodEnd),
    prisma.order.findMany({ where: { customerId: statement.customerId, status: { not: "CANCELLED" } }, select: { dueDate: true } }),
    canShare ? findActiveShareLink("SOA", statement.id) : null,
  ]);
  const balanceStatus = deriveSoaBalanceStatus(openOrders);
  const isPartiallyPaid = computation.totalPayments > 0 && computation.outstandingBalance > 0.01;

  return (
    <div className="max-w-3xl space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">{statement.statementNumber}</h1>
          <Link href={`/soa/customer/${statement.customerId}`} className="text-sm text-slate-500 underline">
            {statement.customer.name}
          </Link>
        </div>
        <div className="flex items-center gap-2">
          {computation.outstandingBalance > 0.01 && <Badge tone={STATUS_TONE[balanceStatus]}>{balanceStatus}</Badge>}
          {isPartiallyPaid && <Badge tone="yellow">Partially Paid</Badge>}
          <Link href={`/soa/${statement.id}/print`} target="_blank">
            <Button type="button" variant="outline" size="sm">
              Generate PDF
            </Button>
          </Link>
        </div>
      </div>

      <Card className="border-l-4 border-l-brand-600">
        <CardContent className="py-4">
          <p className="text-xs font-medium uppercase tracking-wide text-slate-500">Total Outstanding</p>
          <p className="text-3xl font-bold text-brand-700">{formatCurrency(Math.max(computation.outstandingBalance, 0))}</p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Account Summary</CardTitle>
        </CardHeader>
        <CardContent className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-3">
          <Field label="Opening Balance" value={formatCurrency(computation.openingBalance)} />
          <Field label="Charges / New Transactions" value={formatCurrency(computation.totalCharges)} />
          <Field label="Payments / Credits" value={formatCurrency(computation.totalPayments)} />
          <Field label="Adjustments" value={formatCurrency(computation.adjustments)} />
          <Field label="Statement Period" value={`${formatDate(statement.periodStart)} – ${formatDate(new Date(statement.periodEnd.getTime() - 1))}`} />
          <Field label="Generated By" value={statement.generatedBy?.name ?? "—"} />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Transaction Details</CardTitle>
        </CardHeader>
        <Table>
          <THead>
            <TR>
              <TH>Date</TH>
              <TH>Reference</TH>
              <TH>Description</TH>
              <TH>Charge</TH>
              <TH>Payment</TH>
              <TH>Balance</TH>
            </TR>
          </THead>
          <TBody>
            {computation.rows.map((r, i) => (
              <TR key={i}>
                <TD className="whitespace-nowrap text-sm">{formatDate(r.date)}</TD>
                <TD className="text-sm font-medium">{r.reference}</TD>
                <TD className="text-sm text-slate-600">{r.description}</TD>
                <TD>{r.charge > 0 ? formatCurrency(r.charge) : "—"}</TD>
                <TD>{r.payment > 0 ? formatCurrency(r.payment) : "—"}</TD>
                <TD className="font-medium">{formatCurrency(r.runningBalance)}</TD>
              </TR>
            ))}
          </TBody>
        </Table>
        {computation.rows.length === 0 && <p className="p-4 text-sm text-slate-400">No activity in this period.</p>}
      </Card>

      {canShare && (
        <Card>
          <CardHeader>
            <CardTitle>Payment Follow-up</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-wrap gap-2">
            <SendSoaButton statementId={statement.id} />
            <DiscussSoaButton statementId={statement.id} />
          </CardContent>
        </Card>
      )}

      {canShare && (
        <Card>
          <CardHeader>
            <CardTitle>Share Statement</CardTitle>
          </CardHeader>
          <CardContent>
            <DocumentShareManager
              docType="SOA"
              docId={statement.id}
              isCustomer={false}
              activeLink={
                activeShareLink
                  ? {
                      id: activeShareLink.id,
                      token: activeShareLink.token,
                      accessLevel: activeShareLink.accessLevel,
                      expiresAt: activeShareLink.expiresAt ? activeShareLink.expiresAt.toISOString() : null,
                    }
                  : null
              }
            />
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-[11px] font-medium uppercase tracking-wide text-slate-400">{label}</p>
      <p className="text-slate-900">{value}</p>
    </div>
  );
}
